# Generated by Django 5.2.4 on 2025-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist_app", "0002_tasklistmodel_manage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="tasklistmodel",
            options={"ordering": ["id"]},
        ),
    ]
